### ISSUE TITLE
Runtime 22.08 todo

### ISSUE THREAD

**Issue by tinywrkb** [flathub/io.qt.qtwebengine.BaseApp#30]
Document these as f-e-d-c doesn't keep comments in JSON. 

* [ ] Use libxml & libxsl from the runtime. See [bug report](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1336).
* [x] Enable thin archives. See [bug report](https://sourceware.org/bugzilla/show_bug.cgi?id=28138). **edit: [Fixed in Freedesktop SDK 21.08.11](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/b6589037e7c0ac8bc480d1152e83534e8d6cb565)**
* [ ] Remove krb5. See [bug report](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1256)
* [x] Drop python2 if QtWebEngine was updated to 6.3.x.

**Comment by aleixpol** [comment]
f-e-d-c?

**Comment by tinywrkb** [comment]
flatpak-external-data-checker, see [ticket](https://github.com/flathub/flatpak-external-data-checker/issues/192).

**Comment by tinywrkb** [comment]
Closing as it doesn't look like krb5 will be added to the 22.08 runtime, and libxml was added as a disabled config option, so it's documented.
